---
name: Directory-Scratch-Structured
version: 0.02
author:
  - 'Khemir Nadim ibn Hamouda. <nadim@khemir.net>'
abstract: "creates temporary files and directories from a structured description\n"
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Data::TreeDumper: 0
  Directory::Scratch: 0
  Readonly: 0
  Sub::Exporter: 0
  Sub::Install: 0
  Test::Block: 0
  Test::Dependencies: 0
  Test::Distribution: 0
  Test::Exception: 0
  Test::NoWarnings: 0
  Test::Perl::Critic: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
  Test::Spelling: 0
  Test::Strict: 0
  Test::Warn: 0
provides:
  Directory::Scratch::Structured:
    file: lib/Directory/Scratch/Structured.pm
    version: 0.02
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
